### ISSUE TITLE
Background folder

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/video-source-code-create-nft-collection#22]
Hey when i start "npm run generate" i got the message:
Error: ENOENT: no such file or directory, scandir 'C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection\src\main.js:73:6)
    at C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection\src\main.js:87:30)
    at startCreating (C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection\src\main.js:351:20)
    at C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection\index.js:6:3
    at Object.<anonymous> (C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\NFTMinter1000Oversea\\NewCodeErrorFixed\\video-source-code-create-nft-collection/layers/Background/'

But i have changed the config file and there is no directory Background listed.

Here my config changes

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 10,
    layersOrder: [
      { name: 'Backgrounds' },
      { name: 'Body'},
      { name: 'Klamotten'},
      { name: 'Augen'},
      { name: 'Iris' },
      { name: 'Mund' },
      { name: 'Frisur'},
    ],
  },
];

**Comment by gurselcesur** [comment]
I have same problem with you when i run generator i got same error message, did you solve the problem, or anybody solve the problem. (Note: Node.js updated)

**Comment by ChristianErdtmann** [comment]
yes in my case it was just a saving problem.
Save all Files after changes.
then run generate

**Comment by multimellowsofficial** [comment]
> yes in my case it was just a saving problem. Save all Files after changes. then run generate

how do you do that sorry im new and i have the same problem and ive spent like 2hrs looking how to fix and i nearly gave up till i saw your way i dont understand much coding wise and stuff i would really appreciate the help
