### ISSUE TITLE
[Bug]: TypeError: Cannot read property 'edition' of undefined

### ISSUE THREAD

**Issue by bbugs280** [codeSTACKr/video-source-code-create-nft-collection#97]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened!  When i run the uploadMeta.js and genericMeta.js 
Both file generate an error above.

I check in the Meta Files and there isn't such a property. Any idea why this happen?

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
(node:76873) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'edition' of undefined
    at main (/Users/vincent/Documents/DApp/create-10k-nft-collection-main/utils/nftport/uploadMetas.js:28:82)
    at Object.<anonymous> (/Users/vincent/Documents/DApp/create-10k-nft-collection-main/utils/nftport/uploadMetas.js:59:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:76873) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Protect your information

- [X] I Agree

**Comment by Bobata-constantlyafk** [comment]
FIXED! AUG 2022. Go to the "codeSTACKr/create-10k-nft-collection" git repository. Then go to /utils/nftport/uploadFiles.js. After that next to the change branch option you can find change the tag. Change it to v1.2.0 - he updated the code and if you change to 1.2.0 you will find the version that worked for me. Godspeed.
